== Matthew

=== Matthew 5:44 | Praying for enemies

But I say to you, Love your enemies and pray for those who persecute you, so that you may be sons of your Father who is in heaven.

- Who are we to pray for: Our enemies, those who persecute us. 
Why: To be like our Heavenly Father, who gives good to the just and unjust.

Matthew 6:5-8 | Praying in secret
“And when you pray, you must not be like the hypocrites. For they love to stand and pray in the synagogues and at the street corners, that they may be seen by others. Truly, I say to you, they have received their reward. 6 But when you pray, go into your room and shut the door and pray to your Father who is in secret. And your Father who sees in secret will reward you.
7 “And when you pray, do not heap up empty phrases as the Gentiles do, for they think that they will be heard for their many words. 8 Do not be like them, for your Father knows what you need before you ask him.
Two times “when you pray”: Jesus expects his followers to pray, it’s “when” not “if”.
Every prayer has a reward: either recognition from men, or a reward from your Father.

To whom: Our Heavenly Father
Where: In the secret place where no one knows we are praying. 

Matthew 6:9-13 | Our Father
9 Pray then like this:
“Our Father in heaven,hallowed be your name.
10 Your kingdom come,your will be done,    on earth as it is in heaven.
11 Give us this day our daily bread,
12 and forgive us our debts,    as we also have forgiven our debtors.
13 And lead us not into temptation,    but deliver us from evil.

To whom: Our Heavenly Father
